package ar.edu.um.programacion2.trabajo_final.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GrupoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAllPropertiesEquals(Grupo expected, Grupo actual) {
        assertGrupoAutoGeneratedPropertiesEquals(expected, actual);
        assertGrupoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAllUpdatablePropertiesEquals(Grupo expected, Grupo actual) {
        assertGrupoUpdatableFieldsEquals(expected, actual);
        assertGrupoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAutoGeneratedPropertiesEquals(Grupo expected, Grupo actual) {
        assertThat(expected)
            .as("Verify Grupo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoUpdatableFieldsEquals(Grupo expected, Grupo actual) {
        assertThat(expected)
            .as("Verify Grupo relevant properties")
            .satisfies(e -> assertThat(e.getIdGrupo()).as("check idGrupo").isEqualTo(actual.getIdGrupo()))
            .satisfies(e -> assertThat(e.getNombres()).as("check nombres").isEqualTo(actual.getNombres()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoUpdatableRelationshipsEquals(Grupo expected, Grupo actual) {}
}
